name: "Teison EV Charger Control"
version: "1.0.57"
slug: "teison_ev_charger"
description: "Control a Teison EV Charger via cloud API"
hassio_api: true
auth_api: true
panel_icon: "mdi:ev-station"
panel_title: "EvTeisonCharger"
#panel_admin: true
#ingress: true
#ingress_port: 5000
startup: "application"
boot: "auto"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  username: ""
  password: ""
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqttuser"
  mqtt_pass: "mqttpass"
  device_index: 0
  access_token: ""
  pull_interval: 10
schema:
  username: "str"
  password: "str"
  mqtt_host: "str"
  mqtt_port: "int"
  mqtt_user: "str"
  mqtt_pass: "str"
  device_index: "int"
  access_token: "str"
  pull_interval: "int"
ports:
  "5000/tcp": null
webui: "http://[HOST]:[PORT:5000]"
